"""Python client for the Blue Media payment gateway."""

from bluemedia.blik import (
    AUTHORIZATION_CODE_LENGTH,
    BLIK_GATEWAY_ID,
    AuthorizationCodeError,
    authorization_code,
    blik_transaction,
)
from bluemedia.client import (
    DEFAULT_TIMEOUT,
    PRODUCTION_BASE_URL,
    SANDBOX_BASE_URL,
    TRANSACTION_PATH,
    Client,
    GatewayError,
    GatewayStatusError,
    MissingTransportError,
    ResponseVerificationError,
)
from bluemedia.itn import (
    CONFIRMATION_ROOT,
    CONFIRMED,
    ITN_ROOT,
    NOTCONFIRMED,
    Base64DecodeError,
    Confirmation,
    ConfirmationList,
    Notification,
    NotificationList,
    decode_base64,
)
from bluemedia.models import (
    DuplicateElementError,
    MalformedXMLError,
    MissingElementError,
    TransactionInit,
    TransactionStart,
    UnexpectedRootError,
    UnknownElementError,
    XMLParseError,
)
from bluemedia.signing import (
    DEFAULT_ALGORITHM,
    DEFAULT_SEPARATOR,
    ITN_FIELD_ORDER,
    TRANSACTION_FIELD_ORDER,
    TRANSACTION_INIT_FIELD_ORDER,
    DuplicateFieldError,
    UnknownFieldError,
    hash_values,
    ordered_values,
    sign,
    string_to_sign,
    verify,
)

__all__ = [
    "AUTHORIZATION_CODE_LENGTH",
    "AuthorizationCodeError",
    "BLIK_GATEWAY_ID",
    "Base64DecodeError",
    "CONFIRMATION_ROOT",
    "CONFIRMED",
    "Client",
    "Confirmation",
    "ConfirmationList",
    "DEFAULT_ALGORITHM",
    "DEFAULT_SEPARATOR",
    "DEFAULT_TIMEOUT",
    "DuplicateElementError",
    "DuplicateFieldError",
    "GatewayError",
    "GatewayStatusError",
    "ITN_FIELD_ORDER",
    "ITN_ROOT",
    "MalformedXMLError",
    "MissingElementError",
    "MissingTransportError",
    "NOTCONFIRMED",
    "Notification",
    "NotificationList",
    "PRODUCTION_BASE_URL",
    "ResponseVerificationError",
    "SANDBOX_BASE_URL",
    "TRANSACTION_FIELD_ORDER",
    "TRANSACTION_INIT_FIELD_ORDER",
    "TRANSACTION_PATH",
    "TransactionInit",
    "TransactionStart",
    "UnexpectedRootError",
    "UnknownElementError",
    "UnknownFieldError",
    "XMLParseError",
    "__version__",
    "authorization_code",
    "blik_transaction",
    "decode_base64",
    "hash_values",
    "ordered_values",
    "sign",
    "string_to_sign",
    "verify",
]

__version__ = "0.1.0"
